version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/xe:21.3.0
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=oracle123
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: always

networks:
  default:
    name: powerguard-network

volumes:
  oracle-data: